<template>
    <div>
<!-- Blog/İhtiyaç (Gereksinim)     Yazıyı kontrol ett   -->

<div class="header-banner">
    <img src="../img/carousel1_abhgbev.jpg" />
    <h1 class="content">İhtiyaç (Gereksinim) Nedeniyle Tahliye Davasında Dikkat Edilmesi Gerekenler!</h1>
    </div>

      <p class="kutu">
        <ul>
            <li>Bu bültende; 6098 Sayılı Türk Borçlar Kanunu’nun (“TBK”) “Gereksinim, yeniden İnşa, ve imar” başlıklı 350. Maddesinde düzenleme alanı bulan “gereksinim/ihtiyaç nedeniyle tahliye” konusu genel olarak incelenecektir. TBK’nın 350. Maddesi; “Kiraya veren, kira sözleşmesini; 1-Kiralananı kendisi, eşi, altsoyu, üstsoyu veya kanun gereği bakmakla yükümlü olduğu diğer kişiler için konut ya da işyeri gereksinimi sebebiyle kullanma zorunluluğu varsa,…..belirli süreli sözleşmelerde sürenin sonunda, belirsiz süreli sözleşmelerde kiraya ilişkin genel hükümlere göre fesih dönemine ve fesih bildirimi için öngörülen sürelere uyularak belirlenecek tarihten başlayarak bir ay içinde açacağı dava ile sona erdirebilir” düzenlemesini içermektedir.</li>
            <br>
            <li><strong>1- Dava Açma Yönünden;</strong></li>
            <li>TBK’nın 350. Maddesinden de görüleceği üzere sözleşmenin belirli ve belirsiz süreli olmasına göre bir ayrım yapılmaktadır. Bu kapsamda;</li>
            <li>* Sözleşmenin belirli süreli olması halinde sürenin sona ermesi akabinde hiçbir ihtar ve bildirime gerek kalmaksızın bir ay içinde dava ikame edilebilecektir. Bununla birlikte konut ve çatılı iş yerleri için belirli süreli kira sözleşmesinin sonunda TBK’nın 347. Maddesi doğrultusunda kiracının sözleşme süresinin bitiminden en az on beş gün önce bildirimde bulunmaması halinde sözleşme aynı koşullarla bir yıl için uzatılmış sayılacaktır. Bu haliyle de her yıl yenilenerek devam eden bir kira sözleşmesinin varlığı halinde hiçbir ihtar ve bildirime gerek kalmaksızın yenilenen sürenin sonundan itibaren bir ay içinde dava ikame edilebilecektir. Örneğin; 30.03.2021 tarihinde başlayan 1 yıllık süreli bir kira sözleşmesi için 30.03.2022 tarihi sözleşmenin sona erme tarihi olup bu tarihten itibaren 1 ay içinde; 30.04.2022 tarihine kadar bu davanın açılması gerekmektedir. Bununla birlikte TBK 347 dikkate alınarak kiracı tarafından sözleşmenin sona ereceğine dair bir bildirimde bulunulmaması halinde kira sözleşmesi 30.03.2022 – 30.03.2023 dönemi için uzamış sayılacaktır. Bu haliyle de 30.03.2023 tarihinin sona ermesinden itibaren 1 ay içinde; 30.04.2023 tarihine kadar bu davanın açılması gerekmektedir. Ancak aşağıda açıklamasına yer verdiğimiz TBK 353. Maddesi uyarınca en geç süre bitiminde konut ihtiyacı nedeniyle tahliye talep edileceği kiracıya bildirilmiş ise, bir aylık süre sona ermiş olsa dahi kira süresi sona erdiği tarihten sonraki uzayan bir yıllık dönem sonuna kadar tahliye davası açabilecektir.</li>
            <br>
            <li>* Belirsiz süreli kira sözleşmelerinde genel hükümlere göre fesih dönemi ve fesih bildirim süresi dikkate alınmaktadır. TBK’nın 350. Maddesinde; “…belirsiz süreli sözleşmelerde kiraya ilişkin genel hükümlere göre fesih dönemine ve fesih bildirimi için öngörülen sürelere uyularak belirlenecek tarihten başlayarak bir ay içinde açacağı dava ile sona erdirebilir.” hususları belirtilerek fesih süreleri ve dava açma süresi için genel hükümlere atıf yapılmıştır. TBK’nın 328. Maddesinde “Belirsiz süreli kira sözleşmelerinde taraflardan her biri, daha uzun bir fesih bildirim süresi veya başka bir fesih dönemi kararlaştırılmış olmadıkça, yasal fesih dönemlerine ve fesih bildirim sürelerine uyarak sözleşmeyi feshedebilir. Fesih dönemlerinin hesabında, kira sözleşmesinin başlangıç tarihi esas alınır. Sözleşmede veya kanunda belirtilen fesih dönemine veya bildirim süresine uyulmamışsa, bildirim bir sonraki fesih dönemi için geçerli olur” düzenlemesine yer verilmiştir. Bunun devamında ise Taşınmaz ve Taşınır Yapı Kiraları başlıklı Fesih Bildirimi başlıklı TBK’nın 329. Maddesinde ise; “Taraflardan her biri, bir taşınmaza veya taşınır bir yapıya ilişkin kira sözleşmesini yerel âdette belirlenen kira döneminin sonu için veya böyle bir âdetin bulunmaması durumunda, altı aylık kira döneminin sonu için, üç aylık fesih bildirim süresine uyarak feshedebilir.” hususlarına yer verilmiştir. TBK’nın 329. Maddesine uyarınca; belirsiz süreli kira sözleşmelerinde her altı aylık dönem bir fesih dönemi olup kiraya verenin altı aylık fesih döneminden en az 3 ay önce kiracıya bildirimde bulunmak ve altı aylık fesih dönemi dolduktan sonra bir ay içinde davayı açmak zorundadır. Örneğin; 30.03.2021 tarihinde başlayan 1 yıl süreli kira sözleşmesinin sözleşmenin devam etme iradesi gösterilerek 30.03.2022 tarihinden sonra belirsiz süreli hale gelmesi akabinde 29.09.2022 tarihi ilk altı aylık dönem, 29.03.2023 tarihi ikinci altı aylık dönem şeklinde belirlenecektir. Kiraya veren ikinci altı aylık dönemde kira sözleşmesini gereksinim nedeniyle sonlandırmak isterse 29.03.2023 tarihinden en geç üç ay önce, yani 29.12.2022 tarihine kadar karşı tarafa ulaşacak şekilde fesih bildiriminde bulunmuş olması gerekmektedir. Fesih bildiriminin 29.12.2022 tarihine kadar ulaşması halinde kiraya verenin 29.04.2023 tarihine kadar dava açması gerekmektedir. Ayrıca burada dikkat edilmesi gereken önemli hususlardan birisi; fesih bildiriminin noter kanalıyla veya iadeli taahhütlü postayla karşı tarafa gönderilmesi halinde fesih bildiriminin notere verilerek keşide edilme tarihi ya da PTT’ye teslim tarihi değil; tebliğ tarihinin dikkate alınacak olmasıdır. Eğer, fesih bildirimi 29.12.2022 tarihine kadar karşı tarafa ulaşmazsa ya da örneğin 05.01.2023 tarihinde ulaşır ise bu bildirim bir sonraki fesih dönemi olan 29.09.2023 tarihi için geçerli olacak ve bu kapsamda da sona erme tarihi sonrasında 29.10.2023 tarihine kadar söz konusu davanın açılması gerekecektir.</li>
            <br>
            <li>* Genel hükümlere tabi kira sözleşmelerinde kira süresinin sona ermesi halinde sözleşme süresi belirsiz hale gelir. TBK. M. 327/2’de “Taraflar, bu durumda, açık bir anlaşma olmaksızın kira ilişkisini sürdürürlerse, kira sözleşmesi belirsiz süreli sözleşmeye dönüşür.” hususu düzenlenmiştir. Sona erme süresi itibariyle kira ilişkisi devam ettirilerek belirsiz süreli hale gelen kira sözleşmelerinde de her altı aylık dönem bir fesih dönemi olup kiraya verenin altı aylık fesih döneminden en az 3 ay önce kiracıya bildirimde bulunmak ve altı aylık fesih dönemi dolduktan sonra bir ay içinde davayı açmak zorundadır. Burada önemle dikkat edilmelidir ki Konut veya Çatılı İş Yeri için düzenlenen kira sözleşmelerinde bu hüküm uygulanamayacaktır. TBK’nun Kira Sözleşmeleri başlıklı Dördüncü Bölümünün Genel Hükümler alt başlıklı Birinci Ayırımında TBK’nun 327. Maddesi ve sair maddeler düzenlenmiştir. Bunun karşılığında Konut ve Çatılı İşyeri Kiraları alt başlıklı İkinci Ayırım kısmında ise yalnızca Konut ve Çatılı İş Yeri Kira Sözleşmelerine uygulanacak hükümler düzenlenmiştir. Bu durum kanunun lafzından kaynaklanmakla birlikte ayrıca Yargıtay 6. H.D. 2016/657 E ve 2016/2286 K. Sayılı ilamında da “Taşınmaz ve taşınır yapı kiralarıyla ilgili belirsiz süreli kira sözleşmelerinde feshi ihbar süresi Türk Borçlar Kanun'unun 329.maddesi hükmüne göre belirlenir. Kiralananın Konut ve Çatılı İşyerleri Kirasına tabi olması halinde ise; TBK'un 350. maddesine göre kira süresi kendiliğinden bir yıl daha uzar ve dava açma süresi kira bitiminden itibaren bir aylık süreye tabi olur. Bu durumda uyuşmazlığın çözümü için öncelikle kiralananın galip vasfının belirlenmesi ve kiralananın TBK'un genel hükümlerine mi, yoksa konut ve çatılı iş yeri kiralanmasına ilişkin hükümlerine mi tabi olduğu konusunda uzman bilirkişiden denetime elverişli rapor alınması ve varılacak sonuca göre bir karar verilmesi gerekirken..” hususu belirtilerek kesin ayrıma atıfta bulunulmuştur.</li>
            <br>
            <li>TBK’ nın 353. Maddesini de değerlendirmeye almamız gerekirse ilgili maddede “Kiraya veren, en geç davanın açılması için öngörülen sürede dava açacağını kiracıya yazılı olarak bildirmişse, dava açma süresi bir kira yılı için uzamış sayılır.” hususları düzenlenmiştir. Söz konusu madde ve madde gerekçesi dikkate alındığında kiraya veren tarafından daha önce veya en geç dava açma için öngörülen sürede dava açmak yerine dava açılacağına dair bir bildirimde bulunursa dava açma süresi bir kira yılı için uzamış sayılacak olup bu uygulamanın belirsiz süreli kira sözleşmeleri için de uygulanabileceğini söylemek mümkündür (Y.6. H.D. 03.06.2014 T. 2014/4988 E ve 2014/7264 K.)</li>
            <br>
            <li><strong>1- Dava Açma Yönünden</strong></li>
            <li>Kiraya veren ile taşınmaz malikinin birbirinden farklı olması hali uygulamada sıkça karşılaşılan bir durumdur. İhtiyaç nedeniyle tahliye davasında ise davacının; davada taraf olma hakkının olup olmadığı yönünde bazı tereddütler bulunmaktadır. Bu kapsamda Yargıtay kararlarında da sarih olarak Kiraya Veren ile Taşınmaz Malikinin birbirinden farklı olması halinde dahi her ikisi de davada taraf olma ehliyetine sahip olduğu belirtilmektedir. (Y. 3.H.D. 11.10.2017 T. 2017/5469 E ve 2017/13735 K, Y. 6. H.D. 29.01.2015 T. 2014/13824 E ve 2015/1000 K, Y. 6. H.D. 11.09.2014 T. 2014/7730 E ve 2014/9613 K)</li>
            <br>
            <li>Tartışmalı bir diğer husus ise; malik şirketin ortağının konut ihtiyacı sebebiyle gereksinim nedeniyle tahliye davasını açıp açamayacağıdır. Bu kapsamda Yargıtay, şirket yetkilisinin ve ortağının konut ihtiyacı sebebiyle bu davanın açılamayacağı yönünde hüküm tesis etmektedir. (Y. 6.H.D. 16.11.2015 T. 2015/7742 E ve 2015/9922 K.)</li>
            <br>
            <li><strong>3- Gereksinimin Samimi ve Zorunlu Olması Yönünden;</strong></li>
            <li>TBK’nun 350. Maddesine dayanılarak açılan davada; dava şartlarından birisi de bir “gereksinime dayanılması” olup bu gereksinimin de samimi ve zorunlu olması şartı aranmaktadır. Gereksinim sebepleri olarak TBK’da spesifik olarak belirli durumlar sayılmamış olup, içtihatlarda gereksinimin samimi ve zorunlu olması ve bu gereksinimin dava devam ederken de devam etmesi hali aranmaktadır. Söz konusu samimi ve zorunlu olan gereksinim ise her türlü delille ispatlanabilmektedir.</li>
            <br>
            <li>Yargıtay tarafından; reşit olan oğulun aileden ayrı ayrı meskende oturmak istemesi (Y. 6. H.D. 05.11.2015 T. 2015/6245 E ve 2015/9532 K, Yargıtay HGK 23.10.2015 T. 2014/6-224 E ve 2015/2354 K), taşınmazın kendisinin veya ihtiyaçlının iş yerine yakın olması (Y. 6.H.D. 30.10.2013 T. 2013/12007 E ve 2013/14454 K, Y. 6. H.D. 11.03.2015 T. 2015/1031 E ve 2015/2447 K),tahliye tehdidi altında bulunmasa dahi ihtiyaçlının kirada oturması (Y. 6. H.D. 21.03.2013 T. 2013/2188 E ve 2013/4985 K) gereksinimin samimi ve zorunlu olduğu durumlara örnek olarak gösterilmektedir.</li>
            <br>
            <li><strong>Sonuç</strong></li>
            <li>TBK’nun 350. Maddesine dayalı olarak gereksinim nedeniyle açılacak olan tahliye davasında ilk olarak dikkat edilmesi gereken konu fesih ve dava süresidir. Fesih ihtarnamesinin süresinde tebliğ edilmemesi, davanın fesih sürelerine uyulmadan ikame edilmesi halinde açılan davada aleyhe sonuç alınması muhtemel olacaktır. Ayrıca davacının taraf ehliyeti hususu da aktif husumet yönünden önem arz etmekle birlikte davacı; taşınmazın maliki veya kiraya veren olabilmektedir. Bununla birlikte gereksinim ve gereksinimin samimi ve zorunlu olması; esas itibariyle gereksinim sebeplerinin genişliği ve farklılıkları açısından geniş kapsamlı bir konu olup bunun ayrıca değerlendirilmesi ve her türlü delille ispatlanması gereklidir.</li>
        </ul>
        </p>
                                                        
    </div>

</template>