<template>
    <div>
<!-- Blog/Çekişmeli Boşanma Davası -->

<div class="header-banner">
    <img src="../img/hukuk_12.jpg" />
    <h1 class="content">Trafik Kazalarında Tazminat Davaları</h1>
    </div>

     <p class="kutu">

        <ul>
            <li>Trafik kazası nedeniyle maddi ve manevi tazminat davası, en az bir motorlu aracın katıldığı bir kazada ölüm, yaralanma gibi bedensel zararlar ile üçüncü kişilere ait ev, araba, arazi gibi malvarlıklarında meydana gelen zararlarının giderilmesi amacıyla zarara uğrayan kişiler tarafından trafik kazasında sorumluluğu bulunanlara karşı açılan bir tazminat davası türüdür. Trafik kazası tazminatı, uyugulamada hem bedensel hem de malvarlığı zararlarını ifade etmek üzere kullanılmaktadır.</li>
            <br>
            <li>Tazminat davası açılmadan önce, dava açma süresinin ne zaman başladığı ve sona erdiği dikkat edilmesi gereken en önemli konudur. Trafik kazasının meydana geldiği, yani haksız fiilin işlendiği gün, tazminat davası zamanaşımı süresi işlemeye başlar. Trafik kazalarında da tüm haksız fiillere uygulanan iki zamanaşımı süresinden hangisi davacının lehine ise, o zamanaşımı süresi uygulanır. Trafik kazaları nedeniyle tazminat davası zamanaşımı süreleri şunlardır:</li>
            <li>* Tazminat Davası Esas Zamanaşımı Süresi: Trafik kazası nedeniyle zarar görenin, zararı ve faili öğrendiği tarihten itibaren başlayacak 2 yıllık zamanaşımı süresi vardır. Zarara uğrayan, faili ve zararı daha geç öğrense bile her halukarda fiilin işlenmesinden itibaren 10 yıllık zamanaşımı süresi söz konusudur (KTK md.109). Örneğin, 01.01.2017 tarihinde gerçekleşen ölümlü bir trafik kazasında; ölenin yakınları ölüme neden olan fiilden haberdar olmalarına rağmen, faili 01.09.2018 tarihinde öğrendiklerinde, dava zamanaşımı süresi bu tarihten başlayarak 01.09.2020 yılında sona erecektir. Yani, zarara uğrayanlar veya ölenin desteğinden yoksun kalanlar 01.09.2020 tarihinden sonra ölümlü trafik kazası nedeniyle tazminat davası açamayacaktır.</li>
            <li>* Ceza Zamanaşımı Süresi: Trafik kazası nedeniyle bir suç işlenmişse ceza zamanaşımı süreleri de uygulanır (KTK 109/2). Trafik kazalarında yaralanma varsa taksirle adam yaralama suçu; ölüm varsa taksirle adam öldürme suçu meydana gelir. Trafik kazası neticesinde ölüm veya yaralama varsa, ceza kanununda o suç için öngörülen dava zamanaşımı süresi ne ise, maddi ve manevi tazminat davası açma süresi de odur. Ceza kanunundaki temel dava zamanaşımı süresi geçse bile, ceza davası devam ediyorsa, yani ceza hukukundaki “uzamış dava zamanaşımı” devreye girmişse, ceza davası devam ettiği müddetçe herhangi bir zamanaşımı süresine bağlı olmadan trafik kazası nedeniyle tazminat davası açılabilir.</li>
            <br>
            <li>Trafik kazasında yaralanma meydana gelmişse, yaralanan şahsın bizzat kendisi maddi ve manevi tazminat davası açabilir. Yaralanan kişi maluliyet nedeniyle çalışma hayatı boyunca uğrayacağı işgücü kaybı nedeniyle maddi tazminat; trafik kazası nedeniyle uğradığı elem, keder ve üzüntü nedeniyle de manevi tazminat talep edebilir.</li>
            <br>
            <li>Trafik kazası nedeniyle ağır bedensel bir yaralanma vuku bulmuşsa, yaralanan kişinin yakınları (anne, baba, eş, çocuklar, nişanlı) da sadece “manevi tazminat davası” açabilirler (BK md.56). Yargıtay uygulamasında “ağır bedensel yaralanma”, yaralanan kişinin uzuv kaybı yaşaması veya hayati fonksiyonlarını yerine getirememesi olarak kabul edilmektedir. Örneğin; bir gözün kaybedilmesi, kol veya ayaklardan birinin kesilmesi vb. gibi haller ağır bedensel yaralanma olarak değerlendirilmektedir.</li>
            <br>
            <li>Ölümlü trafik kazalarında ise, ölenden yaşarken destek alan herkes maddi ve manevi tazminat davası açabilir. Ölen evliyse eşi ve çocuklarına, bekar ise anne ve babasına destek verdiği karine olarak kabul edilir. Yani, bu kişilerin ölenin desteğinden yararlandıklarını ispat etmelerine gerek yoktur. Ölenin nişanlısı, amcası, dayısı vb. gibi herhangi bir yakınının trafik kazası nedeniyle tazminat (destekten yoksun kalma tazminatı) talep edebilmesi için ölen kişiden yaşarken destek aldığını ispatlaması gerekir.</li>
            <br>
            <li>Trafik kazası hukuki niteliği itibariyle haksız fiil olarak kabul edildiğinden, maddi ve manevi tazminat davası haksız fiil sorumlularına karşı açılır. Ancak, trafik kazalarında haksız fiili bizzat işleyenler dışında da tazminat sorumluları vardır. Trafik kazası neticesinde ölüm, yaralama veya herhangi bir malvarlığı zararı meydana gelmesi halinde aşağıdaki kişilere maddi ve manevi tazminat davası açılabilir:</li>
            <li>* <strong>Aracın Sürücüsü :</strong> Trafik kazasında kusurlu olan aracın sürücüsü aleyhine tazminat davası açılabilir (BK md.49).</li>
            <li>* <strong>Aracın Sahibi :</strong> Aracın sahibi (KTK md.3) kural olarak aracın işleteni olarak kabul edildiğinden trafik kazası nedeniyle tazminat sorumluluğu vardır (2918 sayılı KTK md.85/1).</li>
            <li>* <strong>Aracın İşleteni :</strong> Trafik kazasına karışan aracın işleteni de oluşan her türlü zarardan sorumlu olduğundan işletene de maddi ve manevi tazminat davası açılabilir (2918 sayılı KTK md.85/1). Trafik tescil kayıtlarında aracın sahibi olarak gözüken kimse, aynı zamanda aracın işleteni olarak kabul edilir. Araç sahibi, aracın üzerinde fiili hakimiyeti bulunmadığını, araç için bir başkasının harcamalarda bulunduğunu veya araç üzerindeki ekonomik çıkarın bir başkasına ait olduğunu, işleten sıfatının bulunmadığını kanıtlayabilirse sorumluluktan kurtulabilir. Motorlu aracın bir teşebbüsün unvanı veya işletme adı altında veya bu teşebbüs tarafından kesilen biletle işletilmesi halinde; aracın işleteni meydana gelen zarardan sorumlu olur. Başka bir kişinin aracı kendi hesabına ve tehlikesi kendisine ait olmak üzere işlettiği ve araç üzerinde fiili tasarrufu bulunduğu ispat edilirse, bu kimse de işleten olarak kabul edilir (HGK 2015/2890 karar).</li>
            <li>* <strong>Sigorta Şirketi :</strong> Trafik kazasına karışan aracın Zorunlu Mali Sorumluluk Sigortası (Trafik Sigortası) veya poliçe kapsamına göre İhtiyari Mali Mesuliyet Sigortası (Kasko Sigortası) hangi sigorta şirketi tarafından yapılmışsa, o sigorta şirketi de ölüm, yaralama veya diğer zararlardan sorumludur (KTK md.91). Karayolları Zorunlu Mali Sorumluluk Sigortası Genel Şartlarının A-1.maddesine göre, sigortacı bu poliçede tanımlanan motorlu aracın işletilmesi sırasında bir kimsenin ölümüne veya yaralanmasına veya bir şeyin zarara uğramasına sebebiyet vermesinden dolayı 2918 Sayılı Karayolları Trafik Kanunu’na göre işletene düşen hukuki sorumluluğu, zorunlu sigorta limitlerine kadar temin eder.</li>
            <br>
            <li>Ölümlü veya yaralamalı trafik kazası nedeniyle açılacak maddi ve manevi tazminat davasında birden fazla yetkili mahkeme vardır. Trafik kazası nedeniyle tazminat davasına bakmaya yetkili mahkemeler şunlardır:</li>
            <li>* Davalılardan herhangi birisinin ikametgahı mahkemesinde tüm sorumlululara maddi ve manevi tazminat davası açılabilir (HMK md.6). Örneğin, İstanbul-Bakırköy’de meydana gelen trafik kazasında kusurlu sürücünün ikametgahı İstanbul-Büyükçekmece, araç sahibinin İkametgahı ise İstanbul-Şişli ise; trafik kazası sebebiyle tazminat davası hem Bakırköy Adliyesinde hem de İstanbul-Çağlayan Adliyesinde açılabilir.</li>
            <li>* Trafik kazasının meydana geldiği yer mahkemesinde tazminat davası açılabilir (HMK md.16/1).</li>
            <li>* Trafik kazaları nedeniyle açılacak tazminat davaları, zarar görenin, yani davacının ikametgahı mahkemesinde de açılabilir (HMK md.16/1). Örneğin, İstanbul-Bakırköy’de trafik kazası geçiren bir kişinin ikametgahı İstanbul-Kartal’da ise, tazminat davası İstanbul Anadolu Adliyesinde açılabilir.</li>
            <li>* Trafik sigortası şirketinin merkezinin bulunduğu yer mahkemesinde de maddi ve manevi tazminat davası açılabilir (HMK md.14/2).</li>
            <br>
            <li><strong>Trafik Kazası Tazminat Davasında Zamanaşımı</strong></li>
            <li>Somut olayda; davaya konu kaza 29.04.2010 tarihinde meydana gelmiştir. Mahkemece, tek taraflı kaza olması, davacıların desteğinin de sürücü olarak kaza sırasında vefat ettiği, cezayı gerektiren bir durum bulunmadığı, iki yıllık zamanaşımı süresinin bu davalı yönünden dolduğu gerekçe gösterilerek zamanaşımı sebebiyle davanın reddine karar verilmiştir. Buna göre davacının desteğinin tam kusuru ile neden olduğu ve kendisinin ölümü ile sonuçlanan trafik kazasının aynı zamanda 5237 Sayılı 179 /2. maddesinde düzenlenen ve trafik güvenliğini tehlikeye sokma olarak tanımlanan cezayı gerektiren eylem niteliğinde bulunması; bu eylemle ilgili ceza davasının 66/1-e maddesi uyarınca sekiz yıllık dava zamanaşımı süresine tabi olması; 2918 Sayılı KTK’nun 109/2 maddesi uyarınca bu sürenin görülmekte olan maddi tazminat davası için de geçerli olması; davanın olay tarihi üzerinden sekiz yıl geçmeden açılmış olması karşısında, somut olayda zamanaşımının gerçekleşmediği açıktır (Yargıtay 17.HD - Karar: 2016/5493).</li>
            <br>
            <li>2918 sayılı Karayolları Trafik Yasasının 109. maddesinde motorlu araç kazalarından doğan maddi zararların tazmini için kaza gününden itibaren iki yıllık zamanaşımı süresi öngörülmüş, aynı maddenin ikinci fıkrasında, davanın cezayı gerektiren bir eylemden kaynaklanması durumunda ceza Kanununun öngördüğü ceza zamanaşımının (sürücü,işleten veya diğer sorumlular için fark gözetilmeksizin) uygulanacağı hükme bağlanmıştır. Eylemin suç oluşturması yeterli olup, ayrıca fail hakkında mahkumiyet kararı ile sonuçlanmış bir ceza davasının varlığı gerekmemektedir (HGK - 2001/705 Karar). Kaldı ki; Hukuk Genel Kurulu’nun 2015/1495 karar sayılı kararında, tek taraflı kazalarda dahi, ceza zamanaşımı süresinin uygulanması gerektiği belirtilmiştir. 5237 sayılı TCK.nın 85/1 maddesine5237 sayılı TCK.nın 85/1 maddesine göre “Taksirle bir insanın ölümüne neden olan kişi, iki yıldan altı yıla kadar hapis cezası ile cezalandırılır” hükmü düzenlenmiştir. Buna göre, 66/1-d maddesi gereğince 15 yıl zamanaşımına tabidir. Somut olayda; dava konusu kaza 20.10.2010 tarihinde meydana gelmiştir. Meydana gelen kaza nedeniyle davacıların desteği, kaza tarihinde ölmüştür. Buna göre, dava açılması uzamış ceza zamanaşımına tabi olup, mahkemece yargılama yapılarak sonucuna göre karar verilmesi gerekir (Yargıtay 17. HD - Karar: 2016/375).</li>
            <br>
            <li><strong>Trafik Kazası Tazminat Davasında Kusurun Yansıtılmaması</strong></li>
            <li>Davacıların ölenin salt mirasçısı sıfatıyla değil, destekten yoksun kalan üçüncü kişi sıfatıyla dava açtıklarına, ölüm sebebiyle doğrudan davacılar üzerinde doğan destekten yoksunluk zararının oluşumundaki kusurun davacılara yansıtılamayacağına; dolayısıyla araç sürücüsünün veya işletenin tam kusurlu olmaları halinde, desteğinden yoksun kalan davacıları etkilemeyeceğine; 2918 Sayılı Karayolları Trafik Kanunu ve Karayolları Motorlu Araçlar Zorunlu Mali Sorumluluk Sigortası Genel Şartları’na göre, aracın zorunlu mali sorumluluk sigortacısı davalı sigorta şirketi, işletenin üçüncü kişilere verdiği zararları teminat altına aldığına ve olayda işleten veya sürücü tam kusurlu olsalar bile, destekten yoksun kalan davacılar da zarar gören üçüncü kişi konumunda bulunduğundan, davalı sigorta şirketinin sorumlu olacağına karar vermek gerekir. ( HGK - 2011/411 karar, HGK - 2012/92 karar, HGK 2013/74 karar) Somut olayda, davacıların ölen murisi sürücüsü olduğu araçta %100 kendi kusuruyla vefat ettiği anlaşılmaktadır. Mahkemece yukarıda açıklanan yasa hükümleri ve HGK kararları doğrultusunda davacılar 3.kişi konumunda olduğundan herhangi bir indirim yapılmaksızın davanın kabulüne karar verilmesi gerekir (Yargıtay 17. HD - Karar: 2016/2637).</li>
            <br>
            <li><strong>Ölümlü veya Yaralanmalı Trafik Kazasında Mağdurun Kusuru ve Tazminattan İndirim</strong></li>
            <li>Dava, trafik kazasından kaynaklanan destekten yoksun kalma ve cenaze gideri istemine ilişkindir. Kaza tespit tutanağında yolcu murislerin emniyet kemeri takıp takmadığı tespit edilememiş, olay yeri inceleme raporuna göre yerde biri çocuk dört erkek cesedinin bulunduğu, aracın içerisinde bulunan sürücü ve kadın yolcunun hastaneye kaldırıldığı, kadın yolcunun hastanede vefat ettiği, sürücünün aracın hızını yol, hava ve trafik durumunun gerektirdiği şartlara göre ayarlama kuralını ihlal ettiği belirlenmiş, mahkemece aldırılan kusur bilirkişi raporuna göre kapalı kasa kamyonetin şoför dahil 5 kişilik olup araçta toplam 6 kişinin bulunduğu, sürücünün aracın hızını yol, hava ve trafik durumunun gerektirdiği şartlara göre ayarlama kuralını ve taşıma sınırı üzerinde yolcu alımının yasak olması kuralını ihlal ettiği tespit edilmiş, mahkeme gerekçesinde müteveffaların araçta yolcu olmaları sebebiyle üzerlerine atfedilebilecek herhangi bir kusur bulunmadığı belirtilmiştir.</li>
            <br>
            <li>Davalı taraf, temyiz itirazında yolcu murislerin emniyet kemeri takmamaları ve istiap haddini aşacak şekilde araca binmeleri sebebiyle müterafik kusurlarının olduğunu savunmuştur. Desteklerin, istiap haddini aşacak şekilde araca binmiş olmalarının ve ölüm nedeni itibariyle kaza sırasında zararın artmasını önleyecek güvenlik tedbiri olan emniyet kemeri takıp takmadıkları, takmamış iseler bu durumun müterafik kusur oluşturup oluşturmayacağının, yine soruşturma dosyasındaki bu husustaki maddi olgular da gözetilerek, 818 Sayılı BK.nun 44. maddesi uyarınca tazminattan makul oranda indirim gerekip gerekmediğinin tartışılması ve sonucuna göre karar verilmesi gerekirken, mahkemece bu konuda herhangi bir değerlendirme yapılmadan eksik incelemeyle yazılı şekilde hüküm kurulması bozmayı gerektirmiştir (Yargıtay 17. Hukuk Dairesi - Karar: 2017/515).</li>
        
        
        </ul>
        
        <!-- Bir karayolu taşıtının diğer bir taşıta ya da yayaya çarpması ile meydana gelen trafik 
        kazaları, ölüme, maluliyete varabilen yaralanmalara ve araçlarda hasar ve değer kaybına
         yol açabilmektedir. Tüm bunlar, kişilerde maddi ve manevi kayıplara yol açtığından tazminat
          hukuku kapsamında uyuşmazlıklar meydana getirmektedir. Bu yazımızda, oluşan zararların 
          telafisi için izlenebilecek dava yollarına değineceğiz. Kusur Ölümlü, bedensel... -->
        
        </p>
                                                       
    </div>

</template>